version: "3.8"
services:

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  adminer:
    image: adminer:4.7
    links:
      - postgres:db
    ports:
      - "${ADMINER_PORT:-8008}:8080"

